apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gdp08kpue-go
  janus-idp.io/tekton: gdp08kpue-go
  backstage.io/kubernetes-id: gdp08kpue-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gdp08kpue-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
