apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: gdp08kpue-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gdp08kpue-go 
  name: gdp08kpue-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: gdp08kpue-go 
